quotes = {
    1 : {'en': "Even if you’re on the right track – you’ll get run over if you just sit there.",
         'es': "Incluso si estás en el camino correcto, serás atropellado si te sientas allí.",
         'author': "Arthur Godfrey"},
    2 : {'en': "You cannot escape the responsibility of tomorrow by evading it today.",
         'es': "No puedes escapar de la responsabilidad del mañana evadiéndola hoy.",
         'author': "Abraham Lincoln"},
    3 : {'en': "My advice is to never do tomorrow what you can do today. Procrastination is the thief of time.",
         'es': "Mi consejo es que nunca hagas mañana lo que puedas hacer hoy. La procrastinación es la ladrona del tiempo.",
         'author': "Charles Dickens"},
    4 : {'en': "Motivation is what gets you started. Habit is what keeps you going.",
         'es': "La motivación es lo que te hace comenzar. El hábito es lo que te mantiene en movimiento.",
         'author': "Jim Rohn"},
    5 : {'en': "Whatever you want to do, do it now! There are only so many tomorrows.",
         'es': "Lo que quieras hacer, ¡hazlo ahora! Tan sólo hay muchos mañanas.",
         'author': "Michael Landon"},
    6 : {'en': "Take time to deliberate; but when the time for action arrives, stop thinking and go in.",
         'es': "Tómate el tiempo para deliberar; pero cuando llegue el momento de la acción, deja de pensar y actúa.",
         'author': "Napoleon Bonaparte"},
    7 : {'en': "Begin while others are procrastinating. Work while others are wishing.",
         'es': "Comienza mientras otros están postergando. Trabaja mientras otros lo desean.",
         'author': "William Arthur Ward"},
    8 : {'en': "Waiting is a trap. There will always be reasons to wait – The truth is, there are only two things in life, reasons and results, and reasons simply don’t count.",
         'es': "La espera es una trampa. Siempre habrá razones para esperar. La verdad es que solo hay dos cosas en la vida, razones y resultados, y las razones simplemente no cuentan.",
         'author': "Robert Anthony"},
    9 : {'en': "A year from now you may wish you had started today.",
         'es': "Dentro de un año puede que desees haber comenzado hoy.",
         'author': "Karen Lamb"},
    10: {'en': "He who every morning plans the transactions of that day and follows that plan carries a thread that will guide him through the labyrinth of the most busy life.",
         'es': "El que cada mañana planifica la transacción del día y sigue ese plan, lleva un hilo que lo guiará a través del laberinto de la vida más ocupada.",
         'author': "Victor Hugo"},
    11: {'en': "Procrastination is opportunity’s natural assassin.",
         'es': "La dilación es el asesino natural de la oportunidad.",
         'author': "Victor Kiam"},
    12: {'en': "If you have goals and procrastination you have nothing. If you have goals and you take action, you will have anything you want.",
         'es': "Si tienes metas y procrastinación no tienes nada. Si tiene metas y te pones en acción, tendrás todo lo que deseas.",
         'author': "Thomas J. Vilord"},
    13: {'en': "The only difference between success and failure is the ability to take action.",
         'es': "La única diferencia entre el éxito y el fracaso es la capacidad de actuar.",
         'author': "Alexander Graham Bell"},
    14: {'en': "The least productive people are usually the ones who are most in favor of holding meetings.",
         'es': "Las personas menos productivas son generalmente las que están más a favor de celebrar reuniones.",
         'author': "Thomas Sowell"},
    15: {'en': "It is not because things are difficult that we do not dare, it is because we do not dare that they are difficult.",
         'es': "No es porque las cosas sean difíciles que no nos atrevemos, es porque no nos atrevemos que éstas son difíciles.",
         'author': "Seneca"},
    16: {'en': "It is not because things are difficult that we do not dare, it is because we do not dare that they are difficult.",
         'es': "No es porque las cosas sean difíciles que no nos atrevemos, es porque no nos atrevemos que éstas son difíciles.",
         'author': "Seneca"},
    17: {'en': "Time wasted is existence; used is life.",
         'es': "El tiempo perdido es la existencia; el usado es la vida.",
         'author': "Edward Young"},
    18: {'en': "If we wait for the moment when everything, absolutely everything is ready, we shall never begin.",
         'es': "Si esperamos el momento en que todo, absolutamente todo está listo, nunca comenzaremos.",
         'author': "Ivan Sergeyevich Turgenev"},
    19: {'en': "If you procrastinate when faced with a big difficult problem… break the problem into parts, and handle one part at a time.",
         'es': "Si pospones las cosas cuando te enfrentas a un gran problema... divide el problema en partes y enfréntalas por separado.",
         'author': "Robert Collier"},
    20: {'en': "Perhaps the most valuable result of an education is the ability to make yourself do the thing you have to do, when it ought to be done, whether you like it or not.",
         'es': "Quizás el resultado más valioso de una educación es la capacidad de obligarte a hacer lo que tienes que hacer, cuando debería hacerse, te guste o no.",
         'author': "Thomas Huxley"},
    21: {'en': "My ambition is limited by my laziness.",
         'es': "Mi ambición está limitada por mi pereza.",
         'author': "Charles Bukowski"},
    22: {'en': "Laziness travels so slowly that poverty soon overtakes it.",
         'es': "La pereza viaja tan despacio que la pobreza no tarda en alcanzarla.",
         'author': "Benjamin Franklin"},
    23: {'en': "A lazy man is a watch without spring.",
         'es': "Un hombre con pereza es un reloj sin cuerda.",
         'author': "Jaime Balmes"},
    24: {'en': "There is no road that does not end if it is not opposed by the laziness.",
         'es': "No hay camino que no se acabe si no se le opone la pereza.",
         'author': "Miguel de Cervantes"},
    25: {'en': "Don’t let yesterday take up too much of today.",
         'es': "No dejes que el ayer tome mucho de lo de hoy.",
         'author': "Will Rogers"},
    26: {'en': "Whether you think you can or think you can’t, you are right.",
         'es': "Tanto si crees que puedes como si crees que no puedes, tienes razón.",
         'author': "Henry Ford"},
    27: {'en': "If I had nine hours to chop down a tree, I’d spend the first six sharpening my axe.",
         'es': "Si tuviese nueve horas para talar un árbol, emplearía las seis primeras en afilar mi hacha.",
         'author': "Abraham Lincoln"},
    28: {'en': "Intelligence is the ability to adapt to change.",
         'es': "La inteligencia es la capacidad de adaptarse al cambio.",
         'author': "Stephen Hawking"},
}